# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlEphemeral < Formula
  desc "Plugin for kubectl to create ephemeral containers from a YAML file"
  homepage "https://github.com/embik/kubectl-ephemeral"
  version "0.1.0"
  license "Apache-2.0"

  bottle do
    root_url "https://ghcr.io/v2/embik/tap"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "fa45edf4d9691dbeebb5ab42bd2007e00b2d6f5d18673ebe9e3ba0b64fb7879c"
  end

  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/embik/kubectl-ephemeral/releases/download/v0.1.0/kubectl-ephemeral_darwin_amd64.tar.gz"
      sha256 "6c2f5abbc5c8850b1ce602966ad774d869f1a18798c53f891ab5b5af767ed834"

      def install
        bin.install "kubectl-ephemeral"
      end
    end
    on_arm do
      url "https://github.com/embik/kubectl-ephemeral/releases/download/v0.1.0/kubectl-ephemeral_darwin_arm64.tar.gz"
      sha256 "5d2663d0a452980cb146d2db5f2c120e37891ef3222dbf967974fbfbb8e13439"

      def install
        bin.install "kubectl-ephemeral"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/embik/kubectl-ephemeral/releases/download/v0.1.0/kubectl-ephemeral_linux_amd64.tar.gz"
        sha256 "818cb2ed12575a3f647d961615063c2cd134a9407ac998a2d1cb3b6d1f1eb4a5"

        def install
          bin.install "kubectl-ephemeral"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/embik/kubectl-ephemeral/releases/download/v0.1.0/kubectl-ephemeral_linux_arm64.tar.gz"
        sha256 "ab7229884e47dccfc146b5c9708f2bc1e3c6048527c8d91b523d24dd06608118"

        def install
          bin.install "kubectl-ephemeral"
        end
      end
    end
  end
end
